// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/member/domain/member_repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/core/member/domain/member_repository.go -destination=./internal/core/member/domain/mock_repository/mock_repository.go
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	domain "go-oapi-aidd/internal/core/member/domain"
	reflect "reflect"

	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockMemberQueryRepository is a mock of MemberQueryRepository interface.
type MockMemberQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMemberQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockMemberQueryRepositoryMockRecorder is the mock recorder for MockMemberQueryRepository.
type MockMemberQueryRepositoryMockRecorder struct {
	mock *MockMemberQueryRepository
}

// NewMockMemberQueryRepository creates a new mock instance.
func NewMockMemberQueryRepository(ctrl *gomock.Controller) *MockMemberQueryRepository {
	mock := &MockMemberQueryRepository{ctrl: ctrl}
	mock.recorder = &MockMemberQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberQueryRepository) EXPECT() *MockMemberQueryRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockMemberQueryRepository) FindByID(ctx context.Context, db bun.IDB, id string) (*domain.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, db, id)
	ret0, _ := ret[0].(*domain.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMemberQueryRepositoryMockRecorder) FindByID(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMemberQueryRepository)(nil).FindByID), ctx, db, id)
}
