// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/member/usecase/calculate_point_usecase.go
//
// Generated by this command:
//
//	mockgen -source=./internal/core/member/usecase/calculate_point_usecase.go -destination=./internal/core/member/usecase/mock_usecase/mock_usecase.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	usecase "go-oapi-aidd/internal/core/member/usecase"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCalculatePointUsecase is a mock of CalculatePointUsecase interface.
type MockCalculatePointUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatePointUsecaseMockRecorder
	isgomock struct{}
}

// MockCalculatePointUsecaseMockRecorder is the mock recorder for MockCalculatePointUsecase.
type MockCalculatePointUsecaseMockRecorder struct {
	mock *MockCalculatePointUsecase
}

// NewMockCalculatePointUsecase creates a new mock instance.
func NewMockCalculatePointUsecase(ctrl *gomock.Controller) *MockCalculatePointUsecase {
	mock := &MockCalculatePointUsecase{ctrl: ctrl}
	mock.recorder = &MockCalculatePointUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculatePointUsecase) EXPECT() *MockCalculatePointUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCalculatePointUsecase) Execute(ctx context.Context, input usecase.CalculatePointInput) (usecase.CalculatePointOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(usecase.CalculatePointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCalculatePointUsecaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCalculatePointUsecase)(nil).Execute), ctx, input)
}
