// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/shared/logger/logger.go
//
// Generated by this command:
//
//	mockgen -source=./internal/shared/logger/logger.go -destination=./internal/shared/logger/mock_logger/mock_logger.go
//

// Package mock_logger is a generated GoMock package.
package mock_logger

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(addSource bool, tx context.Context, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", addSource, tx, message)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(addSource, tx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), addSource, tx, message)
}

// Info mocks base method.
func (m *MockLogger) Info(addSource bool, tx context.Context, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", addSource, tx, message)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(addSource, tx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), addSource, tx, message)
}

// Warn mocks base method.
func (m *MockLogger) Warn(addSource bool, tx context.Context, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", addSource, tx, message)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(addSource, tx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), addSource, tx, message)
}
