openapi: 3.0.3
info:
  title: go-oapi-aidd API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: ローカル v1

tags:
  - name: Healthcheck
    description: ヘルスチェックAPI
  - name: Members
    description: 会員API

paths:
  /healthcheck:
    $ref: "./paths/supporting/healthcheck.yaml"
  /members/{memberId}/point-calculations:
    $ref: "./paths/core/member/point_calculations.yaml"

components:
  schemas:
    HealthcheckResponse:
      $ref: "./components/schemas/common/message.yaml"
    ErrorResponse:
      $ref: "./components/schemas/common/message.yaml"
    CalculateMemberPointRequest:
      $ref: "./components/schemas/core/member/calculate_point_request.yaml"
    CalculateMemberPointResponse:
      $ref: "./components/schemas/core/member/calculate_point_response.yaml"
    ErrorAddCodeResponse:
      $ref: "./components/schemas/common/error_response.yaml"
